### ISSUE TITLE
我安装的时候出现了问题，能不能给予些帮助。

### ISSUE THREAD

**Issue by CamusGao** [syscl/Asus-FX50J#3]
我安装的时候出现了问题，确切的说是最多只看到了分区界面。能不能给予些帮助。看你的readme上意思好像是安装上之后完善用的。我的机器机型是FX50JX4720。谢谢。

**Comment by syscl** [comment]
@GggXp 最终只看到分区界面？截个图看看～

**Comment by CamusGao** [comment]
@syscl 现在就是到安装的时候让我插入电源，右上角是电池的状态，不接入电源不能继续安装。然而电源并不能被正确识别。

**Comment by syscl** [comment]
@GggXp 电源可以被正确识别，用我FX50J中的Clover目录

syscl

**Comment by CamusGao** [comment]
@syscl 用你的这里的Clover目录我尝试过，直接看不到安装界面，有一个禁行标识

**Comment by syscl** [comment]
@GggXp 检查你BIOS中的设置是否按照这个教程来

并且附上Verbose模式图

syscl

**Comment by CamusGao** [comment]
@syscl 没有看到你的README中有对BIOS的要求，我的设置是关闭了VT-d，其他的不动。Clover中有-v 加上默认参数启动会在出现一行+++++号提示后直接重启

**Comment by syscl** [comment]
尝试注入内存信息

**Comment by CamusGao** [comment]
@syscl 我现在成功的安装上了macOS，但是还不到能正常用的程度。没有完全按照你这里面来，但是从你这里面吸收了很多东西。看到你这里面只有10.11 中有kext'，是不是代表这里只针对El Captain版本？

**Comment by syscl** [comment]
抱歉我没有这台电脑 只是当初帮同学弄过这台电脑 所以有机会开启并测试了这个项目 你有好的建议可以pull这个项目里面来 这样就可以保持这个项目的持续更新。

你说的没错 这个项目目前只在10.11下面，因为1是我手头上没有这台机子，2是因为同学对系统折腾不多希望有一个稳定可靠的系统，所以我也不敢多折腾，在他10.11完美稳定之后 我就几乎不更新这个项目了。

理论来说，你只要建立了10.12的kext文件夹更新Clover之后就可以驱动10.12了，但是要注意几个Sierra的问题：
1. 触摸板部分功能丢失，你可以用最新的VoodooPS2替代 但是那个驱动并不如AppleSmartTouchPad，可以说AppleSmartTouchPad开发的比Windows下面的触摸板驱动还要好的多
2. Safari在某些网页下面（例如Facebook， youtube）会导致系统瞬间重启，自从10.12以来系统中就出现了很多问题（无关黑苹果）
3. 大写锁定键问题
4. 无法顺利的查看系统日志（需要用命令）这对完善十分不友好

syscl

**Comment by syscl** [comment]
另外 如果要在1011下面完全驱动 需要严格按照我的操作步骤来 因为我不知道你们做了什么导致系统不稳定的因素和扰动。

这个项目是相当稳定可靠的.

syscl
